config/routes.rb
Rails.application.routes.draw do
  resources :status_reports
  resources :projects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/status_report.rb
class StatusReport < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/status_reports_controller.rb
class StatusReportsController < ApplicationController
  before_action :set_status_report, only: [:show, :edit, :update, :destroy]

  # GET /status_reports
  # GET /status_reports.json
  def index
    @status_reports = StatusReport.all
  end

  # GET /status_reports/1
  # GET /status_reports/1.json
  def show
  end

  # GET /status_reports/new
  def new
    @status_report = StatusReport.new
  end

  # GET /status_reports/1/edit
  def edit
  end

  # POST /status_reports
  # POST /status_reports.json
  def create
    @status_report = StatusReport.new(status_report_params)

    respond_to do |format|
      if @status_report.save
        format.html { redirect_to @status_report, notice: 'Status report was successfully created.' }
        format.json { render :show, status: :created, location: @status_report }
      else
        format.html { render :new }
        format.json { render json: @status_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_reports/1
  # PATCH/PUT /status_reports/1.json
  def update
    respond_to do |format|
      if @status_report.update(status_report_params)
        format.html { redirect_to @status_report, notice: 'Status report was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_report }
      else
        format.html { render :edit }
        format.json { render json: @status_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_reports/1
  # DELETE /status_reports/1.json
  def destroy
    @status_report.destroy
    respond_to do |format|
      format.html { redirect_to status_reports_url, notice: 'Status report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_report
      @status_report = StatusReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_report_params
      params.require(:status_report).permit(:project_id, :user_id, :yesterday, :today, :status_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/status_reports_helper.rb
module StatusReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Huddle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/status_reports/_form.html.erb
<%= form_with(model: status_report, local: true) do |form| %>
  <% if status_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status_report.errors.count, "error") %> prohibited this status_report from being saved:</h2>

      <ul>
      <% status_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, id: :status_report_project_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :status_report_user_id %>
  </div>

  <div class="field">
    <%= form.label :yesterday %>
    <%= form.text_area :yesterday, id: :status_report_yesterday %>
  </div>

  <div class="field">
    <%= form.label :today %>
    <%= form.text_area :today, id: :status_report_today %>
  </div>

  <div class="field">
    <%= form.label :status_date %>
    <%= form.date_select :status_date, id: :status_report_status_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/status_reports/edit.html.erb
<h1>Editing Status Report</h1>

<%= render 'form', status_report: @status_report %>

<%= link_to 'Show', @status_report %> |
<%= link_to 'Back', status_reports_path %>

app/views/status_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Status Reports</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>User</th>
      <th>Yesterday</th>
      <th>Today</th>
      <th>Status date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_reports.each do |status_report| %>
      <tr>
        <td><%= status_report.project %></td>
        <td><%= status_report.user %></td>
        <td><%= status_report.yesterday %></td>
        <td><%= status_report.today %></td>
        <td><%= status_report.status_date %></td>
        <td><%= link_to 'Show', status_report %></td>
        <td><%= link_to 'Edit', edit_status_report_path(status_report) %></td>
        <td><%= link_to 'Destroy', status_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status Report', new_status_report_path %>

app/views/status_reports/new.html.erb
<h1>New Status Report</h1>

<%= render 'form', status_report: @status_report %>

<%= link_to 'Back', status_reports_path %>

app/views/status_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @status_report.project %>
</p>

<p>
  <strong>User:</strong>
  <%= @status_report.user %>
</p>

<p>
  <strong>Yesterday:</strong>
  <%= @status_report.yesterday %>
</p>

<p>
  <strong>Today:</strong>
  <%= @status_report.today %>
</p>

<p>
  <strong>Status date:</strong>
  <%= @status_report.status_date %>
</p>

<%= link_to 'Edit', edit_status_report_path(@status_report) %> |
<%= link_to 'Back', status_reports_path %>